// Copyright (c) 2025-2026 Truestamp, Inc.
// SPDX-License-Identifier: Apache-2.0 AND BSD-2-Clause
//
// The fixture prose here quotes short fragments of sigsum.org/sigsum-go@v0.14.1
// (tests/sigsum-submit-test, pkg/merkle/tree_test.go, doc/tools.md),
// BSD-2-Clause, Copyright (c) 2021, The Sigsum Project Authors. The license
// text is LICENSE-sigsum-go in this directory; NOTICE lists it.

package main

// The prose fields of the fixture file. File and line references are to
// sigsum.org/sigsum-go v0.14.1 unless a line says otherwise.

var sources = []string{
	"pkg/merkle/merkle.go:17-37 HashLeafNode = SHA-256(0x00 || leaf), HashInteriorNode = SHA-256(0x01 || left || right), HashEmptyTree = SHA-256(\"\")",
	"pkg/merkle/tree.go:10-43 compact range and getRootHash; the root of an empty range is HashEmptyTree",
	"pkg/merkle/tree.go:45-74 Tree; AddLeafHash returns false and adds nothing when the leaf hash is already in the tree (lines 64-68)",
	"pkg/merkle/tree.go:99-147,211-217 inclusion and ProveInclusion (audit path bottom to top), split = largest power of two smaller than n",
	"pkg/merkle/verify.go:12-17,98-148 pathLength and VerifyInclusion: index < size, exact path length, then the RFC 9162 2.1.3.2 loop",
	"pkg/types/leaf.go:16-20,51-61 Leaf = checksum || signature || key hash (128 bytes), ToHash = HashLeafNode(leaf)",
	"pkg/types/leaf.go:34-37 SignLeafMessage: checksum = SHA-256(message)",
	"pkg/types/proof.go:79-81 InclusionProof.Verify calls merkle.VerifyInclusion",
	"pkg/proof/proof.go:96-139 SigsumProof.FromASCII (size 1 proofs carry no inclusion part)",
	"pkg/proof/proof.go:168-191 SigsumProof.Verify and VerifyNoCosignatures: checksum = SHA-256(message), leaf signature, tree head signature and cosignature policy, then inclusion",
	"pkg/proof/proof_test.go:13-58 TestASCII: two proofs from sigsum-submit-test, size 1 (lines 19-26, root_hash line 24) and size 4 with leaf_index 3 and 2 node_hash (lines 27-38); upstream asserts only the ASCII round trip",
	"pkg/proof/proof_test.go:60-130 TestASCIIV1: the same two proofs in version 1 form; their leaf lines (79, 101) carry the first 2 bytes of the leaf checksum, 5cc0 and 7e28",
	"tests/sigsum-submit-test:31-38 submits proof x for the message printf \"%31s\\n\" \"foo-$x\" with --raw-hash, x = 1..5; lines 44-48 verify each proof. This gives the TestASCII messages (foo-1, foo-4)",
	"pkg/proof/proof_test.go:132-161 TestVerifyNoCosignatures: size 4, leaf_index 3 proof (lines 134-145), message (146-149), log and submit keys (150-151); asserts VerifyNoCosignatures succeeds",
	"pkg/proof/proof_test.go:163-200 TestVerify: size 4, leaf_index 3 proof with a cosignature (lines 165-177), message (178-181), log, submit and witness keys (182-184); asserts Verify succeeds under a 1-of-1 witness policy",
	"pkg/proof/proof_test.go:201-207 mustParsePublicKey",
	"pkg/types/tree_head_test.go:151-167,449-455 TestSignedTreeHeadVerify: the TestVerifyNoCosignatures tree head (size 4, root 7bca01e8...) signed by the same log key; a cross-check, adds no case",
	"pkg/merkle/tree_test.go:354-370 mustHashFromHex and newLeaves: leaf i = HashLeafNode(8-byte big-endian i)",
	"pkg/merkle/tree_test.go:62-87 TestGetRootHash: the empty root literal (line 70) and formula roots for sizes 1..5 over newLeaves(5) (lines 71-75)",
	"pkg/merkle/tree_test.go:89-118 TestInclusion: formula paths for every leaf at size 5 (lines 104-108)",
	"pkg/merkle/tree_test.go:120-159 TestInclusionValid: newLeaves(100); for every 0 <= i < n <= 100 (5050 pairs) ProveInclusion(i, n) must verify, and a math/rand seed 17 flip of one bit of the leaf hash or of one path element must not",
	"pkg/merkle/tree_test.go:256-262 TestConsistency formula nodes h45 and h456 over newLeaves(7); its consistency paths are outside the schema",
	"pkg/merkle/verify.go:19-96 VerifyConsistency (RFC 9162 2.1.4.2), used to check that the two doc/tools.md tree heads are consistent; adds no case",
	"pkg/merkle/verify.go:150-191,270-301 VerifyInclusionTail: verifies a run of leaves ending at the tree size with sigsum's compact range code, which takes every leaf as given (tree.go:26-43, 87-89); with leaf 0's path it checks a whole tree, duplicates included",
	"pkg/policy/config.go:126-152 ParseConfig and pkg/requests/requests.go:71-87 Leaf.FromASCII parse the doc/tools.md policy and add-leaf request",
	"doc/tools.md:268-269 sigsum-key to-hex: the example submitter public key, whose SHA-256 is the key hash on both example proofs' leaf lines",
	"doc/tools.md:338-347 sigsum-submit: by default the message submitted to the log is the SHA256 hash of the input (lines 343-344)",
	"doc/tools.md:419-426 the policy file for the poc.sigsum.org log (log key line 424, quorum none); SHA-256 of that key is the log line of both example proofs",
	"doc/tools.md:429-441 echo \"Hello old friend\" submitted to that log (line 430) and the size 3 proof printed, leaf_index 2, one node_hash (lines 431-440)",
	"doc/tools.md:443-466 echo \"Hello again\" as a request (lines 446-449: message = SHA-256 of the echo output, signature, public_key), then submitted, and the size 4 proof printed, leaf_index 3, two node_hash (lines 454-465); its node_hash 1 is the size 3 proof's leaf hash and its node_hash 2 the size 3 proof's node_hash",
}

var deviations = []string{
	"API, not hashing: merkle.Tree.AddLeafHash (pkg/merkle/tree.go:64-68) returns false and adds nothing when the leaf hash is already in the tree, so a merkle.Tree cannot hold a tree with duplicate leaves, which RFC 9162 allows. The hash functions, merkle.VerifyInclusion and merkle.VerifyInclusionTail are unaffected: the interop program checks that the second AddLeafHash of a leaf hash is refused and that VerifyInclusion still accepts leaf 1 of the two-leaf tree [l0, l0]. One generated tree in this file has duplicate leaves. merkle.Tree refuses its first repeated leaf, so its root and paths are built with merkle.HashLeafNode and merkle.HashInteriorNode in the RFC 9162 recursion; every path verifies with merkle.VerifyInclusion, and merkle.VerifyInclusionTail over all its leaves with leaf 0's path reaches the root.",
}

// dupTreeDesc names the generated duplicate-leaf tree (after dupPrefix).
const dupTreeDesc = "over the leaf data 0, 1, 0, 1, 2, 2, 0 (8-byte big-endian, the newLeaves values of tree_test.go:362-370): leaves 0..1 and 2..3 are the same pair, so the size 4 subtree is HashInteriorNode(h01, h01); leaves 4 and 5 are identical siblings; leaf 6, alone on the right edge, repeats leaf 0. RFC 9162 allows duplicate leaves and merkle.Tree refuses them (tree.go:64-68), so the root is built with merkle.HashLeafNode and merkle.HashInteriorNode in the RFC 9162 recursion, and merkle.VerifyInclusionTail over all seven leaves with leaf 0's path reaches it"

const notesFormat = `sigsum.org/sigsum-go v0.14.1 (BSD-2-Clause, git tag v0.14.1, commit ea106fe53c454bc5b8ece2ba56afc43d0f1f09dc), packages pkg/merkle, pkg/types and pkg/proof. Hashing, tree shape and proofs are RFC 9162 section 2.1: leaf SHA-256(0x00 || data), node SHA-256(0x01 || left || right), empty root SHA-256(""), split at the largest power of two smaller than n, no padding, audit path bottom to top. merkle.VerifyInclusion rejects index >= size, then requires len(path) == pathLength(index, size), where pathLength counts the loop steps that consume a path element, then runs the 2.1.3.2 loop. That is the 2.1.3.2 verdict on every input. The interop program checks this against an independent reference written from the RFC with crypto/sha256 only: roots for sizes 0..100, all 5050 audit paths over newLeaves(100), the verdict on every case in this file, and the verdict on all 10100 materialized TestInclusionValid cases. They all agree, so discrepancies is empty and no case has rfc9162_valid. valid is always merkle.VerifyInclusion's verdict.

Leaf format. A Sigsum leaf is 128 bytes: checksum || signature || key hash, where checksum = SHA-256(message), signature is Ed25519 over the namespaced checksum, and key hash = SHA-256(submitter public key). The leaf hash is HashLeafNode of those 128 bytes. The proofs in proof_test.go give the signature and key hash on their leaf line but not the checksum, so the leaf is rebuilt from the message. TestVerifyNoCosignatures and TestVerify give the message as a literal (32 bytes: 26 spaces, "foo-4", newline). TestASCII does not, but both its proofs came from running tests/sigsum-submit-test, which submits proof x for printf "%%31s\n" "foo-$x" with --raw-hash (lines 31-38). The size 1 proof is foo-1 and the size 4, leaf_index 3 proof is foo-4. Three things confirm this. TestASCIIV1 carries the version 1 form of the same two proofs, whose leaf lines (proof_test.go:79, 101) start with the first 2 bytes of the checksum, 5cc0 and 7e28, and these are the first bytes of SHA-256 of the foo-1 and foo-4 messages. The size 1 root_hash literal equals the rebuilt foo-1 leaf hash. The rebuilt foo-4 leaf verifies against the size 4 root_hash literal. The program also runs the full proof.VerifyNoCosignatures and proof.Verify on the two keyed proofs with upstream's keys (leaf signature, tree head signature, cosignature, inclusion); both pass. The TestASCII proofs' log and submitter public keys are not in the source, so only their Merkle part is checked. The leaves of the size 4 trees other than leaf 3 are not known individually (node_hash 1 is leaf 2's hash, node_hash 2 the hash over leaves 0..1), so those trees appear only as inclusion cases and node hash_checks, not as trees.

upstream_expectation. The two TestASCII proofs are "none": that test asserts only the ASCII round trip, although sigsum-submit-test (set -e) verified each proof when it made them (lines 44-48). TestVerifyNoCosignatures and TestVerify are "valid" because upstream asserts the full verification succeeds. The five TestInclusion paths are "published" because TestInclusion asserts ProveInclusion(i, 5) returns exactly these formula paths over newLeaves(5). They are "valid" because TestInclusionValid asserts that ProveInclusion(i, 5) verifies over the same leaves (newLeaves(5) is a prefix of newLeaves(100)). Every "published" value is either an upstream hex literal, or a leaf or node hash computed with sigsum's own functions from upstream leaf data exactly as the upstream test computes it (newLeaves and the HashInteriorNode formulas in tree_test.go).

The doc/tools.md examples (lines 419-471). The sigsum-submit section shows two messages submitted to the poc.sigsum.org log and the Sigsum proofs it printed: a size 3 proof with leaf_index 2 and one node_hash (lines 430-441), a right-edge proof, and a size 4 proof with leaf_index 3 and two node_hash (lines 446-466). Both leaves are rebuilt the same way as the proof_test.go ones. The input is the echo output, the quoted text and a newline ("Hello old friend" on line 430, "Hello again" on line 446). By default the message is the SHA256 hash of the input (lines 343-344). The leaf checksum is SHA-256(message), and the leaf line gives the signature and key hash. Five checks tie this together, all with sigsum's own parsers and functions. requests.Leaf.FromASCII reads the request on lines 447-449; its message equals SHA-256 of the "Hello again" echo output, and its signature equals the size 4 leaf signature. SHA-256 of the submitter key (line 269) is the key hash on both leaf lines. SHA-256 of the log key in the policy (line 424, read with policy.ParseConfig) is the log line of both proofs. The size 4 proof's node_hash 1 (line 464) is the rebuilt size 3 leaf hash, and its node_hash 2 is the size 3 proof's node_hash. Last, merkle.VerifyConsistency(3, 4) accepts the two roots with the path [size 3 leaf hash, size 4 leaf hash, size 3 node_hash]. Both inclusion proofs verify with merkle.VerifyInclusion and types.InclusionProof.Verify. Their upstream_expectation is "none": the documentation asserts nothing about them. Also, under v0.14.1 neither the leaf signatures (types.Leaf.Verify, proof.VerifyNoCosignatures), the request signature (requests.Leaf.Verify) nor the tree head signatures (types.SignedTreeHead.Verify with the policy key) verify. The program checks that too, so the Merkle proofs are published values while the signatures are not usable. hash_checks carry both 128-byte leaves and the node steps of both proofs.

The duplicate-leaf tree (generated, upstream_expectation "none"). RFC 9162 allows duplicate leaves, and the other trees here have none. The tree has the leaf data 0, 1, 0, 1, 2, 2, 0 (8-byte big-endian, as newLeaves). Leaves 0..1 and 2..3 are the same pair, so the size 4 subtree is HashInteriorNode(h01, h01). Leaves 4 and 5 are identical siblings. Leaf 6, alone on the right edge, repeats leaf 0. merkle.Tree refuses the first repeat (leaf 2), so the root and the seven paths are built with merkle.HashLeafNode and merkle.HashInteriorNode in the RFC 9162 recursion. Every path verifies with merkle.VerifyInclusion and equals RFC 9162 PATH. merkle.VerifyInclusionTail, whose compact range code takes every leaf as given, checks all seven leaves against the root. Because the two halves of the size 4 subtree are equal, leaves 0 and 2 have the same leaf hash and the same path, and it verifies at both indexes.

TestInclusionValid (tree_test.go:120-159) has no literals. The program runs upstream's loop unchanged (upstream.go copies lines 121-158 and adds two recording lines that make no rand calls), with math/rand.New(rand.NewSource(17)) as upstream seeds it. It records every proof and every corruption: 5050 pairs (i, n), 0 <= i < n <= 100, one valid proof and one bit flip each. For a corruption, bitToFlip = r.Intn(256) and hashToFlip = r.Intn(len(proof) + 1); hashToFlip 0 flips the leaf hash and k > 0 flips path[k-1]. "Bit b" means byte b/8 is XORed with 1 << (b %% 8), as upstream does (lines 148, 150), so bit 0 is the low bit of the first byte. All 5050 proofs verify and all 5050 corruptions are rejected, by sigsum and by the reference. The run was with go1.26.8. math/rand (v1) keeps seeded sequences the same across Go releases, so the flips are upstream's. Written out in full, the set would make this file about 9.3 MB, over the 1.5 MB budget, so the file keeps a deterministic subset of %d pairs (%d cases). The rule: every pair with n <= 32 (528 pairs, every index of every size up to 32). For 33 <= n <= 100, i in {0, k-1, k, n-1} with k the largest power of two below n: the first leaf, the last leaf of the left perfect subtree, the first leaf of the right part, and the last leaf. Last, for any (path length, flip target) class that the full run has and the subset lacks, the first pair in upstream order that has it; this step added %d pairs, because the first two rules already cover every class. Every tree size 1..100 therefore has at least one proof and one corruption, every path length 0..7 is present, and all %d (path length, flip target) classes of the full run are present, including a flip of every path position at every length. Each kept pair appears as its proof followed by its corruption, in upstream loop order. The 100 roots rootHashes[0..99] are trees with leaf_data_rule {"encoding": "u64be", "first": 0}: leaf i data is the 8-byte big-endian encoding of i, exactly newLeaves (tree_test.go:362-370).

Probes (upstream_expectation "none", all invalid under sigsum and RFC 9162) are generated structural cases built only from published values and sigsum's own HashInteriorNode. They cover the exact path-length classes. Right-edge truncation: the path stops early and the root is the chain value at that point (for example leaf_index 3, size 4, path [node_hash 1], root HashInteriorNode(node_hash 1, leaf hash); and leaf 4 of the size 5 formula tree with an empty path and root = its own leaf hash). Over-long paths whose extra element is folded into a recomputed root. Also index = size, the sibling index, size + 1, a reversed path, size 2 for a size 1 proof, and index 0 in the empty tree.

Not materialized. TestInclusionBatchValid and TestInclusionTailValid (tree_test.go:161-254) verify multi-leaf proofs with VerifyInclusionBatch and VerifyInclusionTail, and each corruption flips one of several leaves or one element of two paths, which the single-leaf schema cannot express. Their single-leaf proofs are the same ProveInclusion outputs as TestInclusionValid. TestConsistency and TestConsistencyValid (seed 18) are consistency proofs, outside the schema. pkg/types/tree_head_test.go:168-185 has a size 4 root (84ec3e1b...) with no leaves or path, so nothing is checkable at the leaf-hash level. pkg/monitor/client_test.go builds deterministic logs (keys PrivateKey{2}, {3}, seed 10) but checks only tree heads, consistency and batch or tail inclusion, with no hard-coded answers. pkg/submit/submit_test.go uses random keys. pkg/types/proof_test.go and pkg/client/client_test.go serialize placeholder hashes with no Merkle meaning.

API notes (no effect on the fixture). merkle.VerifyInclusion takes 32-byte arrays, so every hash in this file is 32 bytes. SigsumProof.FromASCII refuses tree size 0 and a size 1 proof with an inclusion part. types.InclusionProof parsing refuses more than 63 node hashes (pkg/types/proof.go:14, 50-52), a wire-format limit that merkle.VerifyInclusion does not have. No leaf datum here is 32 bytes (Sigsum leaves, including the doc/tools.md ones, are 128 bytes; newLeaves data, and so the duplicate-leaf tree's, is 8 bytes), so this file exercises a library at the leaf-hash level only. upstream.go holds the copied upstream lines. The lines between "verbatim" markers are byte-identical to upstream, and LICENSE-sigsum-go is the upstream license. The program reads nothing except the -fixtures file (and, with -ours, the library's vectors file). Check mode verifies every entry with sigsum's functions, re-runs the upstream assertions, and requires the file to be byte-identical to what -write regenerates.

Layout. In the truestamp_merkle repository the interop program is interop/go/sigsum-go/, a Go module that requires sigsum.org/sigsum-go v0.14.1, and this file is vectors/interop/sigsum-go.json. From the program directory, go run . -fixtures ../../../vectors/interop/sigsum-go.json -write regenerates this file and then checks it. The library's test suite runs go run . -fixtures <this file> -ours <vectors/merkle.json> there, with absolute paths, and requires exit status 0; -ours also checks the library's own known answers with sigsum-go.`
