// Copyright (c) 2025-2026 Truestamp, Inc.
// SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause
// Contains literals and short error texts quoted from golang.org/x/mod@v0.41.0
// (sumdb/tlog/tlog.go, sumdb/tlog/tlog_test.go, sumdb/tlog/note.go,
// sumdb/tlog/note_test.go, sumdb/tlog/ct_test.go, sumdb/client_test.go),
// BSD-3-Clause, Copyright 2009 The Go Authors; see LICENSE-golang-x-mod and
// NOTICE.

package main

import "fmt"

var sources = []string{
	"sumdb/tlog/tlog.go:80-105 RecordHash = SHA-256(0x00 || data), NodeHash = SHA-256(0x01 || left || right)",
	"sumdb/tlog/tlog.go:70-78 maxpow2, the split: largest power of two strictly smaller than n",
	"sumdb/tlog/tlog.go:237-267 emptyHash literal (SHA-256 of the empty string) returned by TreeHash(0, r)",
	"sumdb/tlog/tlog.go:317-452 ProveRecord (audit path bottom to top) and CheckRecord (index < size, exact path length)",
	"sumdb/tlog/tlog_test.go:272-280 TestEmptyTree asserts TreeHash(0, nil) == sha256.Sum256(nil)",
	"sumdb/tlog/tlog_test.go:59-149 TestTree: leaf data \"leaf %d\" for i in 0..99 (lines 65-66), TreeHash per size (line 77), ProveRecord/CheckRecord for every tree and leaf (lines 134-141), corruption p[k][0] ^= 1 of each proof hash that CheckRecord must reject (lines 142-148); no hard-coded answers",
	"sumdb/tlog/note_test.go:12-29 golden hash TszzRgjTG6xce+z2AG31kAXYKBgQVtCSCE40HmuwBb0= = RecordHash(\"hello world\") (TestFormatTree, TestParseTree)",
	"sumdb/client_test.go:275-311 newTestClient: record texts 0..3 (lines 295-309) added with addRecord (lines 383-412: RecordHash + StoredHashesForRecordHash); line 306 signs tree 1, the client's starting tree",
	"sumdb/client_test.go:53-93 TestClientBadTiles, lines 83-92 \"Bad starting tree hash looks like bad tiles\": a signed tree N 1 with Hash tlog.Hash{} (line 85) must be rejected (line 92)",
	"sumdb/client_test.go:95-109 TestClientFork: tc appends records 4..5 (lines 99-102), fork tc2 appends different records 4..5 (lines 105-108)",
	"sumdb/client_test.go:116-139 recorded SECURITY ERROR text: tc tree 5 root (line 123), tc2 tree 6 root (line 130), TreeHash(5) of tc2 (line 135), ProveTree(6, 5) of tc2 (lines 136-138); lines 141-149 assert prefixes, including T7i+H/8ER4nXOiw4Bj0k (line 148)",
	"sumdb/client.go:430-475 checkTrees: prints TreeHash(older.N) from the newer tree, then tlog.ProveTree(newer.N, older.N)",
	"sumdb/tlog/tile.go:270-278 and 300-452 TileHashReader: the loaded tiles must hash to the tree hash (lines 398-417), so every hash it returns is proven to be in the tree",
	"sumdb/client.go:113-162 Client init: the in-memory latest tree starts as TreeHash(0) (lines 145-151), then mergeLatest of the configured signed tree (lines 153-161)",
	"sumdb/client.go:209-293 Lookup: ParseRecord, mergeLatest of the response's signed tree (line 264), then checkRecord (line 267)",
	"sumdb/client.go:304-424 mergeLatest and mergeLatestMem: checkTrees(latest, tree) for a newer tree (lines 401-404), checkTrees(tree, latest) for an older one (lines 391-399), and a second pass over the configuration after moving forward (lines 320-333)",
	"sumdb/client.go:430-442 checkTrees: TreeHash(older.N) read through TileHashReader(newer) must equal older.Hash, else ErrSecurity (line 475)",
	"sumdb/client.go:479-495 checkRecord: reads stored hash StoredHashIndex(0, id) through TileHashReader(latest) and compares it with RecordHash(data)",
	"sumdb/client_test.go:25-51 TestClientLookup: lookups of record 2 (line 30, latest tree 3 at line 31), record 0 (line 42, latest still tree 3 at line 43) and record 3 (line 49, latest tree 4 at line 50)",
	"sumdb/client_test.go:53-93 TestClientBadTiles: after the flipped tiles, fresh clients look up record 2 (lines 72-73) and, from the stored tree 3, record 3 (lines 80-81)",
	"sumdb/client_test.go:192-239 TestRejectUnauthenticatedLines: record 4 is the line 195 data, the size 5 tree is hashed at line 209, and its lookup must succeed (lines 232-235)",
	"sumdb/client_test.go:245, 278, 318 tile height 2; lines 383-412 addRecord publishes each record's lookup response with signTree(treeSize) (line 400) and its tiles (lines 402-411); lines 414-426 signTree = TreeHash, FormatTree, note.Sign",
}

const notesHead = `Module golang.org/x/mod v0.41.0 (BSD-3-Clause); the code is package sumdb/tlog, and every sources path is relative to the module root. Hashing, tree shape and proofs follow RFC 9162 section 2.1 exactly: leaf SHA-256(0x00 || data), node SHA-256(0x01 || left || right), split at the largest power of two strictly smaller than n (maxpow2), no padding, no duplicated odd node, audit path bottom to top. CheckRecord is recursive rather than the RFC 9162 2.1.3.2 bit loop, but it is equivalent: it rejects t < 0, n < 0 and n >= t, and it fails on any missing or extra path hash. This file's Go program checks this against an independent RFC 9162 reference (MTH, PATH, the 2.1.3.2 verifier) written with crypto/sha256 only: MTH vs TreeHash and PATH vs ProveRecord for every index of every fixture tree and of every upstream TestTree size 1..100, and verifier agreement on every inclusion case, every upstream corruption over sizes 1..100, and structural mutations (index = size, size + 1, extra hash, dropped first or last hash, reversed path, sibling index). They all agree, so deviations is empty and no case carries rfc9162_valid.

Tree size 0: TreeHash(0, r) returns SHA-256("") = e3b0c442...b855 (the emptyHash literal at tlog.go:237-244), not a zero hash, and it never calls the reader (TreeHash(0, nil) works). The fixture carries it both as empty_root and as a tree of size 0. ProveRecord(t=0, n) and CheckRecord(p, t=0, ...) both return "tlog: invalid inputs", so no inclusion proof exists for an empty tree; the tree_size 0 edge cases below record CheckRecord's answer, which is always invalid. At the other end, tlog cannot work with more than 2^62 leaves: maxpow2 (sumdb/tlog/tlog.go:70-78) never returns for n above 2^62, since 1<<63 is negative and 1<<64 is 0 in int64. CheckRecord therefore does not return for a tree_size above 2^62 once leaf_index is in range and the path is not empty (it still answers at once for an index out of range or an empty path), and ProveRecord and TreeHash, which split with the same helper, do not return at such sizes either. No case here comes near that size, and the program never hands tlog such a size read from a file.

Published answers are few. TestTree in tlog_test.go derives nothing from hard-coded values: it only compares tlog's own code paths with each other (StoredHashes/TreeHash, ProveRecord/CheckRecord, and the tile readers). The hard-coded answers are: the empty hash; RecordHash("hello world") in note_test.go; the SECURITY ERROR text recorded in a comment in sumdb/client_test.go TestClientFork (lines 116-139); and the all-zero starting tree hash of TestClientBadTiles (client_test.go:83-92). The SECURITY ERROR text gives the roots of four trees over the test log's record texts (sizes 4, 5, 5 and 6; line 148 asserts a prefix of the tc2 size 5 root), two leaf hashes, and a consistency proof ProveTree(6, 5) = [leaf 4, leaf 5, MTH(D[0:4])]. All reproduce with tlog. The schema has no consistency section, so that proof is not a fixture entry; its three elements appear as hash_checks and as the size 4 tree root, and the program confirms that tlog.ProveTree(6, 5) reproduces it, that CheckTree accepts it for tc2's roots, and that CheckTree rejects tc's forked size 5 root. The comment's line 121 reads "go.sum database tree!" with a stray "!"; the asserted text at line 144 has none, and the hash on line 123 reproduces. TestClientBadTiles hands the client a signed tree of size 1 whose hash is tlog.Hash{} (32 zero bytes) and requires the lookup to fail; upstream detects it through tile hashes, not CheckRecord. It is the one published inclusion case: record 0 of newTestClient (the only leaf of a size 1 tree) at index 0, empty path, the all-zero root, upstream_expectation invalid, and CheckRecord rejects it. Its valid counterpart is the generated tree of size 1 that newTestClient signs at client_test.go:306 (root = RecordHash(record 0)) and that tree's one proof.

How the client_test.go cases are labeled. Upstream's client tests never call tlog.CheckRecord. They assert inclusion through sumdb.Client, which reads a record's stored hash through tlog.TileHashReader, whose tiles must hash to the signed tree hash (sumdb/tlog/tile.go:398-417). Client.checkRecord (sumdb/client.go:479-495) compares that hash, read from the client's latest tree, with RecordHash of the record data, and Client init checks the configured signed tree against its own tiles through checkTrees (client.go:153-161, 320-333 and 430-442). A lookup that upstream requires to succeed therefore asserts exactly the statement an inclusion case encodes (leaf leaf_index of the tree of tree_size with this root), and a signed tree that upstream requires the client to reject asserts its negation. So each client_test.go case is labeled by what upstream requires of the client: "valid" where a lookup that must succeed authenticates that record in that tree, "invalid" for the one tree the client must reject (TestClientBadTiles lines 83-92, where init fails with "checking tree#1: downloaded inconsistent tile"), and "none" for every other proof, which no upstream line decides. Each labeled case's name ends with the upstream lines. The valid ones are: record 0 in the signed tree of size 1 (Client init before the first lookup at lines 30, 73, 103, 109 and 232); records 2 and 0 in the size 3 tree (lines 30-31 and 72-73; lines 42-43, where the response carries tree 1 but the client's latest tree is 3); record 3 in the size 4 tree (lines 49-50 and 80-81); tc's record 4 in tc's size 5 tree (line 103); tc2's record 5 in tc2's size 6 tree (line 109); and record 4 in the TestRejectUnauthenticatedLines size 5 tree (lines 232-235). The program replays each of these clients with tlog alone. It publishes each test log's tiles as addRecord does (client_test.go:402-411, tile height 2), runs init, mergeLatest's checkTrees and checkRecord through tlog.TileHashReader, and requires every upstream outcome, including the ErrSecurity of TestClientFork lines 111-114. It takes the labels from that replay, once over the upstream records and once over the fixture's own trees, and CheckRecord agrees with every label.

Client trees. Besides the four published trees, the fixture holds newTestClient's signed trees of size 1, 2 and 3 (signTree at client_test.go:306, and at line 400 as records 1 and 2 are added) and the TestRejectUnauthenticatedLines tree of size 5 (records 0..3 and the record at line 195, TreeHash at line 209), with every proof over each. No upstream line states their roots, so they are generated. The size 2 tree is served only with the lookup of record 1, which no test makes, so its proofs are all "none".

No upstream file hard-codes an inclusion proof path, so every other inclusion case is generated with tlog.ProveRecord and tlog.NodeHash, and valid comes from tlog.CheckRecord. "generated: ProveRecord over published ..." cases cover every index of the four published client_test trees, labeled as described above; for tc2's size 6 tree at indexes 4 and 5, and tc2's size 5 tree at index 4, every path element and the root are published literals. "generated: ... TestTree" cases use the upstream leaf data "leaf %d": all proofs for sizes 1..16 (upstream asserts valid) and, for each, every upstream corruption p[k][0] ^= 1, named after the upstream failure message "corrupt proof hash #k" (upstream asserts invalid). Upstream runs sizes 1..100. To keep the file small the fixture carries trees for sizes 1..16 and 100 and proofs for sizes 1..16; the program still runs the whole 1..100 range, with every upstream corruption, without storing it.`

const notesOmitted = `Omitted: sumdb/tlog/ct_test.go TestCertificateTransparency fetches live data from ct.googleapis.com/logs/argon2020 (skipped with -short). Its only literal, the size 3654490 tree hash AuIZ5V6sDUj1vn3Y1K85oOaQ7y+FJJKtyRTl1edIKBQ=, cannot be reproduced without that log's entries. The doc-comment example nND/nri/U0xuHUrYSy0HtMeal2vzD9V4k/BO79C+QeI= (size 2, sumdb/tlog/note.go:50) has no stated leaf data. tile_test.go tests tile storage (tampered tiles), not proofs over leaf hashes. TestTree's consistency proofs (tlog_test.go:186-212) have no hard-coded values and fall outside this inclusion-only schema.

Running it: in the truestamp_merkle repository the program is at interop/go/x-mod-sumdb-tlog/ and this file at vectors/interop/x-mod-sumdb-tlog.json. From the program directory, go run . -fixtures ../../../vectors/interop/x-mod-sumdb-tlog.json checks this file and prints one "OK fixtures" line, or one "FAIL fixtures" line per problem and exit status 1. go run . -fixtures ../../../vectors/interop/x-mod-sumdb-tlog.json -write regenerates the file from the upstream literals and tlog first, then checks it. Adding -ours ../../../vectors/merkle.json also checks the library's own vectors with tlog and prints an "OK ours" line. -fixtures is required, and a bad command line is one "FAIL usage" line. The program reads no file except those two paths. It needs Go 1.26 and golang.org/x/mod v0.41.0, pinned by go.sum and fetched once into the module cache. The BSD-3-Clause text of golang.org/x/mod is in LICENSE-golang-x-mod in the program directory, and the NOTICE file there lists which files hold upstream material. The fixture is self-contained, so an ExUnit test can load it with no Go toolchain; the Go program is the separate regenerate-and-audit step, which the library's opt-in go_interop test tag runs (mix test --include go_interop).`

// buildNotes assembles the notes; the edge case paragraph takes its numbers
// from trapCounts, so it cannot drift from the cases.
func buildNotes(ts trapStats, nEdges int, n map[string]int) string {
	edge := fmt.Sprintf(`Edge cases (%d, names "generated: edge \"<kind>\": ..."), for the classes upstream never asks CheckRecord about. All are built over the TestTree leaf data for tree sizes 1..16 with tlog's own functions, all have upstream_expectation none, and CheckRecord rejects every one; the RFC 9162 2.1.3.2 reference agrees on each. The kinds, and how many cases a verifier missing one rule would accept (so that rule alone rejects them): "index = tree_size" (%d: the last leaf's own proof and root, leaf_index set to tree_size; the RFC loop without its index check accepts %d, an index-bit fold that ignores tree_size and path length accepts %d). "index >= tree_size, low bits kept" (%d: every leaf's own proof and root, leaf_index m + 2^K for 2^K the smallest power of two >= tree_size; the RFC loop without its index check accepts %d, the index-bit fold %d). "index >= tree_size, int64 max" (%d: the last leaf's proof and root, leaf_index 2^63 - 1; %d and %d). "tree_size 0" (%d: empty path with leaf = root = SHA-256(""), empty path with leaf = root = RecordHash("leaf 0"), empty path with root SHA-256(""), and the size 2 proof of leaf 0 with tree_size 0; the index-bit fold accepts %d, the RFC loop without its index check %d, since sn = -1 never reaches 0). "path one short" (%d: ProveRecord's path with its top element dropped, root = the TreeHash of the child subtree of the top split that holds the leaf; CheckRecord accepts %d of these shortened paths as proofs inside that subtree, the RFC loop without its length rules accepts %d, the index-bit fold %d. In %d of them the leaf is in the right subtree and the RFC loop runs out of path with fn == sn != 0, the right-edge termination class). "path one long, extra hash folded on the left" (%d: ProveRecord's path plus RecordHash("leaf n") on top, root NodeHash(extra, TreeHash(n)), which is what a verifier that keeps folding past the top computes; the RFC loop without its length rules accepts %d). "path one long, extra hash folded on the right" (%d: the same path, root NodeHash(TreeHash(n), extra); %d of them, those with n a power of two, equal TreeHash(n + 1) and ProveRecord(n + 1, m), the size n + 1 proof with tree_size understated; the index-bit fold accepts %d).`,
		nEdges,
		ts.total[edgeIndexEqSize], ts.noIndex[edgeIndexEqSize], ts.bits[edgeIndexEqSize],
		ts.total[edgeIndexPlusPow], ts.noIndex[edgeIndexPlusPow], ts.bits[edgeIndexPlusPow],
		ts.total[edgeIndexMax], ts.noIndex[edgeIndexMax], ts.bits[edgeIndexMax],
		ts.total[edgeSizeZero], ts.bits[edgeSizeZero], ts.noIndex[edgeSizeZero],
		ts.total[edgeShort], ts.shortSubtree, ts.noLength[edgeShort], ts.bits[edgeShort], ts.shortRightEdge,
		ts.total[edgeLongLeft], ts.noLength[edgeLongLeft],
		ts.total[edgeLongRight], ts.nextSize, ts.bits[edgeLongRight])
	entries := fmt.Sprintf(`Every entry name starts with "published:" (the value is an upstream literal: empty_root, %d hash_checks, %d trees, %d inclusion case), "generated:" (produced by tlog over upstream leaf data: %d trees and %d inclusion cases) or "derived:" (%d hash_checks, SHA-256 values computed from upstream leaf data or published hashes that no upstream file states). upstream_expectation is "valid" on %d cases, "invalid" on %d and "none" on %d. Leaf data here is variable length (record texts, "leaf %%d"), so a 32-byte-leaf API should use leaf_hashes and treat leaf_data as provenance. No tree is large enough to need leaf_data_rule, so it is null everywhere.`,
		n["hash_checks_published"], n["trees_published"], n["inclusion_published"],
		n["trees_generated"], n["inclusion_generated"], n["hash_checks_derived"],
		n["expect_valid"], n["expect_invalid"], n["expect_none"])
	return notesHead + "\n\n" + edge + "\n\n" + entries + "\n\n" + notesOmitted
}
