// Copyright (c) 2025-2026 Truestamp, Inc.
// SPDX-License-Identifier: Apache-2.0

// Command production-logs checks the production-logs interop fixture: Rekor
// proofs from sigstore-go v1.3.0, rekor v1.5.4, rekor-tiles v0.1.11 and the
// sigstore-conformance suite, the transparency-dev golden log from tessera
// v1.0.4 and serverless-log, and the ics23 v0.11.0 Tendermint vectors, all held
// to transparency-dev/merkle v0.0.2 and an RFC 9162 reference.
//
// In the truestamp-merkle-elixir repository the program is
// interop/go/production-logs/ and its fixture is
// vectors/interop/production-logs.json. From the program directory:
//
//	go run . -fixtures ../../../vectors/interop/production-logs.json                               check the fixture
//	go run . -fixtures ../../../vectors/interop/production-logs.json -write                        regenerate it, then check it
//	go run . -fixtures ../../../vectors/interop/production-logs.json -ours ../../../vectors/merkle.json   also check the library's vectors
//
// -fixtures is required. Upstream data is vendored under testdata/ (see NOTICE)
// and compiled in, so nothing outside this module directory is read except the
// -fixtures and -ours paths. Success prints one OK line per check ("OK fixtures
// ..." and, with -ours, "OK ours ..."); every problem is one line starting
// "FAIL fixtures ", "FAIL ours " or "FAIL usage: ", and the exit status is 1.
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

// moduleName names this check on its OK and FAIL lines, as
// moduleName@version with the spaces of the version string replaced by "+".
const moduleName = "production-logs"

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

const usage = `usage: go run . -fixtures <path> [-write] [-ours <path>]
  -fixtures <path>  the fixture file, vectors/interop/production-logs.json (required)
  -write            regenerate the fixture file from the vendored upstream data, then check it
  -ours <path>      also check the library's vectors/merkle.json with transparency-dev/merkle
`

// label is moduleName@version with no spaces.
func label(version string) string {
	return moduleName + "@" + strings.ReplaceAll(version, " ", "+")
}

// oneLine keeps every FAIL message on a single line (transparency-dev/merkle's
// root-mismatch error spans several).
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// pathFlag is a string flag that must be given a non-empty value, at most once.
type pathFlag struct {
	value string
	set   bool
}

func (p *pathFlag) String() string { return p.value }

func (p *pathFlag) Set(s string) error {
	switch {
	case p.set:
		return errors.New("given more than once")
	case s == "":
		return errors.New("needs a non-empty path")
	}
	p.value, p.set = s, true
	return nil
}

func run(args []string, stdout, stderr io.Writer) (code int) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(stdout, "FAIL usage: internal error:", oneLine(fmt.Sprint(r)))
			code = 1
		}
	}()

	fl := flag.NewFlagSet(moduleName, flag.ContinueOnError)
	fl.SetOutput(io.Discard)
	var fixtures, ours pathFlag
	fl.Var(&fixtures, "fixtures", "")
	fl.Var(&ours, "ours", "")
	write := fl.Bool("write", false, "")
	if err := fl.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			fmt.Fprint(stderr, usage)
			return 0
		}
		fmt.Fprintln(stdout, "FAIL usage:", oneLine(err.Error()))
		return 1
	}
	if fl.NArg() > 0 {
		fmt.Fprintln(stdout, "FAIL usage:", oneLine(fmt.Sprintf("unexpected argument %q (flags only)", fl.Arg(0))))
		return 1
	}
	if !fixtures.set {
		fmt.Fprintln(stdout, "FAIL usage: -fixtures <path> is required")
		return 1
	}

	ok := phase(stdout, "fixtures", func(w io.Writer) bool { return checkFixtureFile(fixtures.value, *write, w) })
	if ours.set {
		ok = phase(stdout, "ours", func(w io.Writer) bool { return checkOursFile(ours.value, w) }) && ok
	}
	if !ok {
		return 1
	}
	return 0
}

// phase runs one check and turns an unexpected panic into a single
// "FAIL <name> internal error" line.
func phase(out io.Writer, name string, check func(io.Writer) bool) (ok bool) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintf(out, "FAIL %s internal error: %s\n", name, oneLine(fmt.Sprint(r)))
			ok = false
		}
	}()
	return check(out)
}

// checkFixtureFile is the fixture check: regenerate the file from the vendored
// upstream data (writing it with -write), then re-derive every value in it and
// require it to equal the regenerated bytes. It prints one OK line or FAIL lines.
func checkFixtureFile(fixturesPath string, write bool, out io.Writer) bool {
	failLine := func(msg string) { fmt.Fprintln(out, "FAIL fixtures", oneLine(msg)) }
	regenerated, b := buildBytes()
	if regenerated == nil {
		for _, e := range b.errs {
			failLine("upstream: " + e)
		}
		return false
	}
	if write {
		if err := os.WriteFile(fixturesPath, regenerated, 0o644); err != nil {
			failLine("write: " + err.Error())
			return false
		}
	}

	raw, err := os.ReadFile(fixturesPath)
	if err != nil {
		failLine("read: " + err.Error())
		return false
	}
	f, err := parseFixture(raw)
	if err != nil {
		failLine("parse: " + err.Error())
		return false
	}

	c := &checker{}
	c.checkFixture(f)
	if string(raw) != string(regenerated) {
		c.fail("the file differs from the one regenerated from the vendored upstream data (run with -write to regenerate)")
	}
	if len(raw) > 1500000 {
		c.fail("the file is %d bytes, over the 1.5 MB budget", len(raw))
	}

	if len(c.errs) > 0 {
		for _, e := range c.errs {
			failLine(e)
		}
		return false
	}
	fmt.Fprintf(out, "OK fixtures %s: %d hash checks, %d trees (%d leaves, %d leaf proofs), %d inclusion (%d valid, %d invalid; %d published, %d generated; upstream asserts %d valid, %d invalid), %d rfc9162 overrides, %d discrepancies, %d upstream literal checks\n",
		label(f.Version), c.hashChecks, c.trees, c.treeLeaves, c.treeProofs, c.inclusion, c.valid, c.invalid,
		c.published, c.generated, c.upstreamValid, c.upstreamInvalid, c.overrides, len(f.Discrepancies), b.literalChecks)
	return true
}

// checkOursFile is the -ours check of the library's vectors/merkle.json. It
// prints one OK line or FAIL lines.
func checkOursFile(oursPath string, out io.Writer) bool {
	raw, err := os.ReadFile(oursPath)
	if err != nil {
		fmt.Fprintln(out, "FAIL ours", oneLine("read: "+err.Error()))
		return false
	}
	lines, ok := checkOurs(raw)
	for _, l := range lines {
		fmt.Fprintln(out, l)
	}
	return ok
}
