// Copyright (c) 2025-2026 Truestamp, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// encodeVarint is adapted from github.com/cosmos/ics23/go@v0.11.0 proof.go:67-76
// encodeVarintProto, and a comment below quotes the test-case names "tm batch
// exist" and "tm batch nonexist" from its vectors_data_test.go:136-137
// (Apache-2.0). License text: LICENSE-ics23; see NOTICE. The
// tree sizes are numbers cited from github.com/confio/proofs-tendermint@v0.6.1
// Makefile:17-24, a module with no LICENSE file; nothing else is taken from it.

package main

// The Tendermint vectors of github.com/cosmos/ics23 (Apache-2.0), vendored from
// the repository's testdata/tendermint at tag go/v0.11.0 (commit
// 16ead2358595639df8ee8c31306ac0eeda2e904f; the directory sits outside the Go
// module github.com/cosmos/ics23/go@v0.11.0, whose go/ tree is identical to the
// tag's). They were generated by github.com/confio/proofs-tendermint (testgen,
// Makefile:14-24) from tendermint v0.33.2 crypto/merkle SimpleProofsFromMap,
// whose tree has the RFC 9162 shape over sorted keys. A leaf is
// SHA-256(0x00 || varint(len key) || key || varint(32) || SHA-256(value)); an
// inner op is SHA-256(0x01 || left || right) with the sibling in the op's prefix
// (left sibling) or suffix (right sibling). ics23 carries no leaf index and no
// tree size.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math/bits"
	"sort"
	"strings"

	ics23 "github.com/cosmos/ics23/go"
	"github.com/transparency-dev/merkle/rfc6962"
)

// Tree sizes: the last argument of each testgen-simple call in
// github.com/confio/proofs-tendermint@v0.6.1 Makefile:17-24 (the same numbers
// since v0.3.1 for the single files and v0.5.0 for the batch files). The module
// ships no LICENSE file; only these numbers are taken from it.
var ics23Files = []struct {
	file     string
	size     uint64
	makeLine int
}{
	{"exist_left.json", 987, 17},
	{"exist_middle.json", 812, 18},
	{"exist_right.json", 1261, 19},
	{"nonexist_left.json", 813, 20},
	{"nonexist_middle.json", 691, 21},
	{"nonexist_right.json", 1535, 22},
	{"batch_exist.json", 1801, 23},
	{"batch_nonexist.json", 1807, 24},
}

// Upstream assertions on these files (github.com/cosmos/ics23/go@v0.11.0):
// go/vectors_test.go:9-39 TestVectors verifies every single file
// (go/vectors_data_test.go:43-48); go/vectors_test.go:41-75 TestBatchVectors
// verifies one item of each batch file: "tm batch exist" refsTMExist[10] and
// "tm batch nonexist" refsTMNonexist[3] (go/vectors_data_test.go:136-137).
var ics23BatchAsserted = map[string]int{
	"batch_exist.json":    10,
	"batch_nonexist.json": 3,
}

// ics23SizeScan bounds the scan for sizes that fit a file's proofs.
const ics23SizeScan = 4096

type ics23Vector struct {
	Root  string `json:"root"`
	Proof string `json:"proof"`
	Key   string `json:"key"`
	Value string `json:"value"`
	Items []struct {
		Key   string `json:"key"`
		Value string `json:"value"`
	} `json:"items"`
}

type ics23Exist struct {
	label    string
	ex       *ics23.ExistenceProof
	asserted string // upstream test asserting it, or ""
	neighbor string // "", "left" or "right" (of a non-existence proof)
	group    int    // non-existence proof number within the file, -1 otherwise
}

// encodeVarint is the protobuf varint that ics23 LengthOp_VAR_PROTO prepends,
// adapted from github.com/cosmos/ics23/go@v0.11.0 proof.go:67-76 encodeVarintProto.
func encodeVarint(l int) []byte {
	var res []byte
	for l >= 1<<7 {
		res = append(res, uint8(l&0x7f|0x80))
		l >>= 7
	}
	return append(res, uint8(l))
}

func ics23LeafData(key, value []byte) []byte {
	vh := sha256.Sum256(value)
	d := append(encodeVarint(len(key)), key...)
	d = append(d, encodeVarint(len(vh))...)
	return append(d, vh[:]...)
}

// ics23Sides maps inner ops to RFC 9162 path elements and sibling sides.
func ics23Sides(ex *ics23.ExistenceProof) (path [][]byte, siblingLeft []bool, err error) {
	for i, op := range ex.Path {
		switch {
		case op.Hash != ics23.HashOp_SHA256:
			return nil, nil, fmt.Errorf("inner op %d hash %v", i, op.Hash)
		case len(op.Prefix) == 1 && op.Prefix[0] == 1 && len(op.Suffix) == 32:
			path = append(path, op.Suffix)
			siblingLeft = append(siblingLeft, false)
		case len(op.Prefix) == 33 && op.Prefix[0] == 1 && len(op.Suffix) == 0:
			path = append(path, op.Prefix[1:])
			siblingLeft = append(siblingLeft, true)
		default:
			return nil, nil, fmt.Errorf("inner op %d has prefix %d bytes, suffix %d bytes", i, len(op.Prefix), len(op.Suffix))
		}
	}
	return path, siblingLeft, nil
}

type ics23FileResult struct {
	file     string
	size     uint64
	feasible string
	repeats  []string // labels of proofs that repeat an earlier proof of the same leaf in the file
}

func (b *builder) ics23() []ics23FileResult {
	var results []ics23FileResult
	spec := ics23.TendermintSpec
	seenLeaf := map[string]bool{}
	for _, fdesc := range ics23Files {
		var v ics23Vector
		if err := json.Unmarshal(readVendored("ics23/testdata/tendermint/"+fdesc.file), &v); err != nil {
			b.fail("ics23 %s: %v", fdesc.file, err)
			continue
		}
		pb, err1 := hex.DecodeString(v.Proof)
		root, err2 := hex.DecodeString(v.Root)
		if err1 != nil || err2 != nil {
			b.fail("ics23 %s: hex %v %v", fdesc.file, err1, err2)
			continue
		}
		var cp ics23.CommitmentProof
		if err := cp.Unmarshal(pb); err != nil {
			b.fail("ics23 %s: protobuf %v", fdesc.file, err)
			continue
		}
		calc, err := cp.Calculate()
		b.expect(err == nil && bytes.Equal(calc, root), "ics23 %s: CommitmentProof.Calculate() is not the published root", fdesc.file)
		dcp := ics23.Decompress(&cp)
		n := fdesc.size

		var exists []ics23Exist
		isBatch := strings.HasPrefix(fdesc.file, "batch_")
		addNon := func(prefix string, ne *ics23.NonExistenceProof, asserted string, group int) {
			if ne.Left != nil {
				exists = append(exists, ics23Exist{fmt.Sprintf("%snon-existence proof of absent key %q, left neighbor", prefix, ne.Key), ne.Left, asserted, "left", group})
			}
			if ne.Right != nil {
				exists = append(exists, ics23Exist{fmt.Sprintf("%snon-existence proof of absent key %q, right neighbor", prefix, ne.Key), ne.Right, asserted, "right", group})
			}
		}
		switch p := dcp.Proof.(type) {
		case *ics23.CommitmentProof_Exist:
			key, _ := hex.DecodeString(v.Key)
			val, _ := hex.DecodeString(v.Value)
			b.expect(bytes.Equal(p.Exist.Key, key) && bytes.Equal(p.Exist.Value, val), "ics23 %s: proof key/value is not the file's", fdesc.file)
			b.expect(ics23.VerifyMembership(spec, root, &cp, key, val), "ics23 %s: VerifyMembership false", fdesc.file)
			exists = append(exists, ics23Exist{"existence proof", p.Exist, "TestVectors (go/vectors_test.go:9-39)", "", -1})
		case *ics23.CommitmentProof_Nonexist:
			key, _ := hex.DecodeString(v.Key)
			b.expect(bytes.Equal(p.Nonexist.Key, key), "ics23 %s: proof key is not the file's", fdesc.file)
			b.expect(v.Value == "", "ics23 %s: non-existence file has a value", fdesc.file)
			b.expect(ics23.VerifyNonMembership(spec, root, &cp, key), "ics23 %s: VerifyNonMembership false", fdesc.file)
			addNon("", p.Nonexist, "TestVectors (go/vectors_test.go:9-39)", 0)
		case *ics23.CommitmentProof_Batch:
			entries := p.Batch.Entries
			b.expect(len(entries) == len(v.Items), "ics23 %s: %d batch entries for %d items", fdesc.file, len(entries), len(v.Items))
			membership := 0
			for i := 0; i < len(entries) && i < len(v.Items); i++ {
				key, _ := hex.DecodeString(v.Items[i].Key)
				val, _ := hex.DecodeString(v.Items[i].Value)
				asserted := ""
				if ics23BatchAsserted[fdesc.file] == i {
					asserted = fmt.Sprintf("TestBatchVectors (go/vectors_test.go:41-75, go/vectors_data_test.go:%d)", map[string]int{"batch_exist.json": 136, "batch_nonexist.json": 137}[fdesc.file])
				}
				if ex := entries[i].GetExist(); ex != nil {
					b.expect(bytes.Equal(ex.Key, key) && bytes.Equal(ex.Value, val), "ics23 %s item %d: entry key/value is not the item's", fdesc.file, i)
					if ics23.VerifyMembership(spec, root, &cp, key, val) && ics23.BatchVerifyMembership(spec, root, &cp, map[string][]byte{string(key): val}) {
						membership++
					}
					exists = append(exists, ics23Exist{fmt.Sprintf("item %d existence proof", i), ex, asserted, "", -1})
				} else if ne := entries[i].GetNonexist(); ne != nil {
					b.expect(bytes.Equal(ne.Key, key) && len(val) == 0, "ics23 %s item %d: entry key is not the item's", fdesc.file, i)
					if ics23.VerifyNonMembership(spec, root, &cp, key) && ics23.BatchVerifyNonMembership(spec, root, &cp, [][]byte{key}) {
						membership++
					}
					addNon(fmt.Sprintf("item %d ", i), ne, asserted, i)
				} else {
					b.fail("ics23 %s item %d: empty batch entry", fdesc.file, i)
				}
			}
			b.expect(membership == len(v.Items), "ics23 %s: ics23 (batch) membership verification holds for %d of %d items", fdesc.file, membership, len(v.Items))
			b.icsBatchItemsVerified += membership
		default:
			b.fail("ics23 %s: unexpected proof type %T", fdesc.file, dcp.Proof)
			continue
		}
		b.expect(isBatch == (len(v.Items) > 0), "ics23 %s: batch/items mismatch", fdesc.file)

		// Per existence proof: leaf, sides, index at the generator's size, three verifiers.
		type placed struct {
			e     ics23Exist
			key   []byte
			path  [][]byte
			sides []bool
			idx   uint64
			ok    bool
		}
		var ps []placed
		var repeats []string
		firstLabel := map[string]string{}
		for _, e := range exists {
			ex := e.ex
			b.expect(ex.CheckAgainstSpec(spec) == nil, "ics23 %s %s: does not match TendermintSpec", fdesc.file, e.label)
			leaf, err := ex.Leaf.Apply(ex.Key, ex.Value)
			if err != nil {
				b.fail("ics23 %s %s: LeafOp.Apply: %v", fdesc.file, e.label, err)
				continue
			}
			ld := ics23LeafData(ex.Key, ex.Value)
			b.expect(bytes.Equal(leaf, rfc6962.DefaultHasher.HashLeaf(ld)) && bytes.Equal(leaf, refLeaf(ld)), "ics23 %s %s: LeafOp.Apply is not SHA-256(0x00 || leaf data)", fdesc.file, e.label)
			path, sides, err := ics23Sides(ex)
			if err != nil {
				b.fail("ics23 %s %s: %v", fdesc.file, e.label, err)
				continue
			}
			// every inner op, applied by ics23, equals the RFC node combination
			r := leaf
			for i, op := range ex.Path {
				next, err := op.Apply(r)
				want := refNode(r, path[i])
				if sides[i] {
					want = refNode(path[i], r)
				}
				b.expect(err == nil && bytes.Equal(next, want), "ics23 %s %s: inner op %d is not the RFC node hash", fdesc.file, e.label, i)
				r = next
			}
			b.expect(bytes.Equal(r, root), "ics23 %s %s: chain does not reach the root", fdesc.file, e.label)
			b.expect(ex.Verify(spec, root, ex.Key, ex.Value) == nil, "ics23 %s %s: ExistenceProof.Verify rejects", fdesc.file, e.label)
			idx, ok := refIndexFromSides(n, sides)
			b.expect(ok, "ics23 %s %s: no leaf index of a size %d tree has these sides", fdesc.file, e.label, n)
			if ok {
				got := refSiblingLeft(idx, n)
				same := len(got) == len(sides)
				for i := 0; same && i < len(got); i++ {
					same = got[i] == sides[i]
				}
				b.expect(same, "ics23 %s %s: derived index %d does not reproduce the sides", fdesc.file, e.label, idx)
			}
			ps = append(ps, placed{e, ex.Key, path, sides, idx, ok})
			if first, dup := firstLabel[hx(leaf)]; dup {
				repeats = append(repeats, fmt.Sprintf("%s repeats %s", e.label, first))
			} else {
				firstLabel[hx(leaf)] = e.label
			}
			if !seenLeaf[hx(leaf)] {
				seenLeaf[hx(leaf)] = true
				b.f.HashChecks = append(b.f.HashChecks, HashCheck{
					Name:     fmt.Sprintf("ics23 go/v0.11.0 testdata/tendermint/%s %s: leaf data = varint(%d) || key %q || varint(32) || SHA-256(value %q); hash = ics23 LeafOp.Apply with the TendermintSpec leaf op", fdesc.file, e.label, len(ex.Key), ex.Key, ex.Value),
					Kind:     "leaf",
					InputHex: sp(hx(ld)),
					Hash:     hx(leaf),
				})
			}
			upstream := "none"
			assertion := "no upstream test asserts this item (the generator emitted it as a valid proof; ics23 verifies it)"
			if e.asserted != "" {
				upstream = "valid"
				assertion = "upstream " + e.asserted + " asserts it verifies"
			}
			b.addPublished(Inclusion{
				Name: fmt.Sprintf("ics23 go/v0.11.0 testdata/tendermint/%s %s for key %q: leaf_index %d derived from the inner-op sides; tree_size %d is the generator's claim (proofs-tendermint v0.6.1 Makefile:%d), not proven by the vector; %s",
					fdesc.file, e.label, ex.Key, idx, n, fdesc.makeLine, assertion),
				LeafHash:            hx(leaf),
				LeafIndex:           idx,
				TreeSize:            n,
				Path:                hxs(path),
				Root:                hx(root),
				UpstreamExpectation: upstream,
			}, ex)
		}

		// Structural checks that tie the derived indexes to the claimed size:
		// sorted keys must have strictly increasing indexes, non-existence
		// neighbors must be adjacent (or at the edge), and the generator's left
		// and right picks are leaves 0 and n-1 (helpers/helpers.go:62-73).
		constraints := func(n uint64, idxOf func(p placed) (uint64, bool)) bool {
			byKey := map[string]uint64{}
			groups := map[int][2]int64{}
			for _, p := range ps {
				idx, ok := idxOf(p)
				if !ok {
					return false
				}
				if prev, seen := byKey[string(p.key)]; seen && prev != idx {
					return false
				}
				byKey[string(p.key)] = idx
				if p.e.group >= 0 {
					g, seen := groups[p.e.group]
					if !seen {
						g = [2]int64{-1, -1}
					}
					if p.e.neighbor == "left" {
						g[0] = int64(idx)
					} else {
						g[1] = int64(idx)
					}
					groups[p.e.group] = g
				}
			}
			keys := make([]string, 0, len(byKey))
			for k := range byKey {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for i := 1; i < len(keys); i++ {
				if byKey[keys[i]] <= byKey[keys[i-1]] {
					return false
				}
			}
			for _, g := range groups {
				switch {
				case g[0] >= 0 && g[1] >= 0 && g[1] != g[0]+1:
					return false
				case g[0] < 0 && g[1] != 0:
					return false
				case g[1] < 0 && uint64(g[0]) != n-1:
					return false
				}
			}
			return true
		}
		b.expect(constraints(n, func(p placed) (uint64, bool) { return p.idx, p.ok }), "ics23 %s: derived indexes break key order or neighbor adjacency at the claimed size %d", fdesc.file, n)
		switch fdesc.file {
		case "exist_left.json":
			b.expect(len(ps) == 1 && ps[0].idx == 0, "ics23 exist_left.json: index is not 0")
		case "exist_right.json":
			b.expect(len(ps) == 1 && ps[0].idx == n-1, "ics23 exist_right.json: index is not n-1")
		}

		// Which sizes up to ics23SizeScan would the vectors alone allow? (Reported
		// in the notes; a right-edge proof fits unboundedly many sizes.)
		var fits []uint64
		for m := uint64(1); m <= ics23SizeScan; m++ {
			if constraints(m, func(p placed) (uint64, bool) { return refIndexFromSides(m, p.sides) }) {
				fits = append(fits, m)
			}
		}
		containsClaim := false
		for _, m := range fits {
			containsClaim = containsClaim || m == n
		}
		b.expect(containsClaim, "ics23 %s: the claimed size %d is not among the sizes the vector allows", fdesc.file, n)
		desc := ranges(fits)
		// A last-leaf path (every sibling on the left) of length L fits exactly
		// the sizes n with popcount(n-1) = L, so say that instead of listing them.
		allLeft, pathLen := len(ps) > 0, len(ps[0].sides)
		for _, p := range ps {
			allLeft = allLeft && len(p.sides) == pathLen
			for _, s := range p.sides {
				allLeft = allLeft && s
			}
		}
		if allLeft && len(fits) > 0 {
			rule := 0
			for m := uint64(1); m <= ics23SizeScan; m++ {
				if bits.OnesCount64(m-1) == pathLen {
					rule++
				}
			}
			b.expect(rule == len(fits), "ics23 %s: last-leaf size rule gives %d sizes, scan found %d", fdesc.file, rule, len(fits))
			desc = fmt.Sprintf("%d sizes between %d and %d (a last-leaf path of %d left siblings fits every n with popcount(n-1) = %d)", len(fits), fits[0], fits[len(fits)-1], pathLen, pathLen)
		}
		results = append(results, ics23FileResult{fdesc.file, n, desc, repeats})
	}
	return results
}

// ranges renders a sorted list of sizes as "a..b, c, d..e (N sizes)".
func ranges(xs []uint64) string {
	if len(xs) == 0 {
		return "none"
	}
	var parts []string
	start, prev := xs[0], xs[0]
	flush := func() {
		if start == prev {
			parts = append(parts, fmt.Sprintf("%d", start))
		} else {
			parts = append(parts, fmt.Sprintf("%d..%d", start, prev))
		}
	}
	for _, x := range xs[1:] {
		if x == prev+1 {
			prev = x
			continue
		}
		flush()
		start, prev = x, x
	}
	flush()
	return fmt.Sprintf("%s (%d sizes)", strings.Join(parts, ", "), len(xs))
}
